export interface OrderInsertInterface extends Document {
    "[CuentaCliente]": string,
    "[OrderTrabajo]": string,
    "[NLocal]": string,
    "[Local_Longitud]": string,
    "[Local_Latitud]": string,
    "[FecAgendada]": Date, 
    "[UnSolicitadas]": string,
    "[Supervisor]": string,
    "[RUT_Cliente]": string,
    "[Comuna_Cliente]": string,
    "[Region_Cliente]": string,
    "[Longitud]": string,
    "[Latitud]": string,
    "[Estado]": string,
    "[EsReagendamiento]": number,
    "[CanalVenta]": string,
    "[TipoDespacho]": string,
}
